name: Deploy Front to GitHub Pages

on:
  push:
    branches:
      - gh-pages
  # Permet de lancer le déploiement manuellement depuis l'interface GitHub au besoin
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # On prépare et on upload le dossier pré-compilé
  prepare-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # On prend directement le dossier dist qui a été poussé sur le repo
          path: .

  # On déploie sur GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prepare-and-upload

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4